INSERT INTO stickers (title, stickerPic) VALUES ('spy-family-anya-peace-512x512.png','https://imagizer.imageshack.com/img924/916/nxuDNu.png');
INSERT INTO stickers (title, stickerPic) VALUES ('chibi-charizard', 'https://imagizer.imageshack.com/img924/2913/nHwxRh.png' );
INSERT INTO stickers (title, stickerPic) VALUES ('cute-kurama', 'https://imagizer.imageshack.com/img923/9232/x6JkRS.png');
INSERT INTO stickers (title, stickerPic) VALUES ('demon-slayer-nezuko-kamado', 'https://imagizer.imageshack.com/img922/5346/4PFClB.png');
INSERT INTO stickers (title, stickerPic) VALUES ('dskny-inosuke-evil', 'https://imagizer.imageshack.com/img923/6449/eRFrOY.png');
INSERT INTO stickers (title, stickerPic) VALUES ('duct-tape-pickle-rick', 'https://imagizer.imageshack.com/img922/5296/QP0zFO.png');
INSERT INTO stickers (title, stickerPic) VALUES ('fairy-tail-happy', 'https://imagizer.imageshack.com/img924/1376/KW9V04.png');
INSERT INTO stickers (title, stickerPic) VALUES ('enthusiastic-pikachu', 'https://imagizer.imageshack.com/img923/7210/8Xr9pR.png');
INSERT INTO stickers (title, stickerPic) VALUES ('inuyasha-sitting' , 'https://imagizer.imageshack.com/img922/705/TxlJnP.png');
INSERT INTO stickers (title, stickerPic) VALUES ('jojo-josuke-higashikata', 'https://imagizer.imageshack.com/img922/3372/NzjggX.png');
INSERT INTO stickers (title, stickerPic) VALUES ('jujutsu-kaisen-satoru-gojo', 'https://imagizer.imageshack.com/img923/7978/uuHyj5.png');
INSERT INTO stickers (title, stickerPic) VALUES ('jujutsu-kaisen-itadori-surprised' , 'https://imagizer.imageshack.com/img924/9337/rtBo5j.png');
INSERT INTO stickers (title, stickerPic) VALUES ('luo-xiaohei', 'https://imagizer.imageshack.com/img922/8299/tkw8pM.png');
INSERT INTO stickers (title, stickerPic) VALUES ('little-witch-academia-akko-broom', 'https://imagizer.imageshack.com/v2/512x512q90/924/XJ5mer.png');
INSERT INTO stickers (title, stickerPic) VALUES ('sailor-moon-luna-cat', 'https://imagizer.imageshack.com/img922/4334/vW9Zyp.png');
INSERT INTO stickers (title, stickerPic) VALUES ('mha-all-might-smile', 'https://imagizer.imageshack.com/img923/9595/7AefN2.png');
INSERT INTO stickers (title, stickerPic) VALUES ('spy-family-anya-smirk' , 'https://imagizer.imageshack.com/img923/7935/pBf5m2.png');
INSERT INTO stickers (title, stickerPic) VALUES ('rick-pizza', 'https://imagizer.imageshack.com/img922/6177/ylEX8t.png');
INSERT INTO stickers (title, stickerPic) VALUES ('
Hunter-x-Hunter-Smiling-Gon', 'https://imagizer.imageshack.com/img924/7057/oHmQ9U.png');
INSERT INTO stickers (title, stickerPic) VALUES ('one piece', 'https://imagizer.imageshack.com/img922/7513/t4Bdcq.png');
INSERT INTO stickers (title, stickerPic) VALUES ('frog-my-hero', 'https://imagizer.imageshack.com/img923/4868/NGgyZE.png');
INSERT INTO stickers (title, stickerPic) VALUES ('totoro-and-mei-kusakabe', 'https://imagizer.imageshack.com/img923/4148/aa3apn.png');
INSERT INTO stickers (title, stickerPic) VALUES ('toradora-taiga-aisaka' , 'https://imagizer.imageshack.com/img924/4424/Azze0j.png');
INSERT INTO stickers (title, stickerPic) VALUES ('umaru-doma-chibi', 'https://imagizer.imageshack.com/img922/9882/iWg88x.png');
INSERT INTO stickers (title, stickerPic) VALUES ('death-note-chibi', 'https://imagizer.imageshack.com/img922/9108/UoKzNM.png');